val noPaymentUri : Uri = Uri.parse("swan_bank_pay://uk.ac.swansea.dascalu.dvmicc.swan_bank/pay")
val intent = Intent("uk.ac.swansea.dascalu.dvmicc.swan_bank.intent.action.LOGIN")
intent.addCategory(Intent.CATEGORY_HOME)
intent.setDataAndType(noPaymentUri, "text/plain")
startActivity(intent)